import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <div className="container mx-auto mt-10">{children}</div>
                <div className="mt-5"></div>
            </body>
        </html>
    );
}
